### ISSUE TITLE
[BUG] Mod name has incorrect grammar and underscore when used with an indicator mod

### ISSUE THREAD

**Issue by V-Boy** [andrew0030/Pandoras-Creatures#18]
**Describe the bug**
Title

**To Reproduce**
1. Startup MC with HWYLA or The One Probe
2. Stare at a PC mob
3. Notice the buggy name of the mod

**Expected behavior**
Should be something like Pandora's Creatures, instead of Pandoras_creature

**Screenshots**
![2020-10-06_11 22 54](https://user-images.githubusercontent.com/40730042/95278442-cce7a280-0815-11eb-8b0b-ad705d8854ee.png)

**Versions**
1.16.3

**Comment by andrew0030** [comment]
That screen is added by HWYLA meaning if you think something is wrong with it you should report it to the developers of HWYLA.
As for the name that is "buggy", I highly doubt the mod is intending to display the name, as I dont think there would be any way for it to know it. What I think is going on here, is that HWYLA takes the MODID and modifies that, (the MODID of Pandoras Creatures is: pandoras_creatures).
I did try to replicate this issue but with the latest version of HWYLA and Pandoras Creatures the issue seems to be gone.
So, make sure you have the latest version of HWYLA and try again, if you still have this problem please report it to the developers of HWYLA.
