### ISSUE TITLE
[CRASH] Optifine x Acidic Archvine

### ISSUE THREAD

**Issue by Jevaderp** [andrew0030/Pandoras-Creatures#6]
**To Reproduce**
The crash has happened pretty sporadically and at unexpected moments, but it has always happened in the Nether with the Acidic Archvine involved and with Optifine running as well. Without Optifine it doesn't seem to be happening.

**Crash log**
https://pastebin.com/eNdumhvX
https://pastebin.com/GADBzKRR
https://pastebin.com/Z63Wniz5

**Additional context**
I don't think it makes much of a difference, but this happened while playing the modpack Harrowing Adventures by Darkfiend009 on Curseforge that has Pandoras Creatures in it.

**Comment by andrew0030** [comment]
Hm Im having trouble recreating the crash I also installed optifine and my mod but it seems to work fine I walked through the nether and everything was normal. Perhaps try a different optifine or forge version?

**Comment by Jevaderp** [comment]
I made a new world in creative with the same seed and everything, flew around for a good 30 minutes or so and it didn't crash either. It happens super random too. Sometimes I can do stuff in the Nether for quite some time before any crash happens and other times it happens more than once in 10 minutes.

I've got the latest versions of both Forge and Optifine as far as I'm aware. Pretty sure Optifine only works with the most recent Forge version too. It had some compatibility issues on a previous version from what I gathered.

**Comment by andrew0030** [comment]
Ok so, I'm still failing to replicate it so it. You also mentioned that this only happens when optifine is installed. I tried running it with optifine and it worked, ofc I cant know for sure as you stated that its a random crash but I also haven't had any other crash reports due to this problem. I would say go through your optifine settings and try to figure out, what it is that crashes the mod. If thats still not it, if you cant replicate the crash without optifine the problem is very likely not on my end, and it is very hard to figure out what exactly it is that causes this, because optifine is not open source. And that means there is no way for me to tell what it is they do that would cause problems in this situation.

**Comment by Vaelzan** [comment]
Even if you can't replicate it, I can see a clear bug in the code there just by looking at the crash log and the line it is pointing to. 
https://github.com/andrew0030/Pandoras-Creatures/blob/52afe39389c415852cc60b2a134eca7ad281f297/src/main/java/andrews/pandoras_creatures/entities/goals/TargetUnderneathGoal.java#L79

This line doesn't perform a null check, but in the code just above, the nearestTarget is being set by a method that can potentially return null (https://github.com/andrew0030/Pandoras-Creatures/blob/52afe39389c415852cc60b2a134eca7ad281f297/src/main/java/andrews/pandoras_creatures/entities/goals/TargetUnderneathGoal.java#L70).

It can be solved just by adding a null check inside startExecuting() to ensure that the archvine actually has a targeted entity.

**Comment by Vaelzan** [comment]
getAttackTarget() can return null in https://github.com/andrew0030/Pandoras-Creatures/blob/52afe39389c415852cc60b2a134eca7ad281f297/src/main/java/andrews/pandoras_creatures/entities/goals/TargetUnderneathGoal.java#L79

You might think that it can't possibly be null because you're setting the target in the line immediately before it, but Forge emits a LivingSetAttackTargetEvent when you set the target, so another mod could be manipulating it in some way. Although you can't reproduce it, adding a null check on the result of getAttackTarget() would add safety there.

**Comment by andrew0030** [comment]
Okey thanks for pointing that out, I will make sure to add a null check.
